### ISSUE TITLE
zImage.armel didn't have any boot message.

### ISSUE THREAD

**Issue by superabiliter** [firmadyne/firmadyne#104]
I use firmadyne to simulate a firmware which I extracted from nandflash. But as I follow the step in README.md. There aren't any log in "qemu.inital.serial.log" file. So I tried to use the bare kernel without rootfs with followed command "qemu-system-arm -m 256 -kernel zImage.armel -M virt -serial stdio". I didn't got any log again. The only things I got is a terminal "compat_monitor0 console".It seems like a monitor of QEMU.Then I tried mipsel kernel in similary command. I got the correct message "Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)". I can't figure out where the wrongs come from with armel kernel. QEMU version or armel kernel issues ?
[    0.000000] Linux version 2.6.32.70 (vagrant@vagrant-ubuntu-trusty-64) (gcc version 5.3.0 (GCC) ) #1 Thu Feb 18 01:44:57 UTC 2016
[    0.000000] 
[    0.000000] LINUX started...
[    0.000000] Config serial console: console=ttyS0,38400n8r
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU revision is: 00019300 (MIPS 24Kc)
[    0.000000] FPU revision is: 00739300
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 00001000 @ 00000000 (reserved)
[    0.000000]  memory: 000ef000 @ 00001000 (ROM data)
[    0.000000]  memory: 00606000 @ 000f0000 (reserved)
[    0.000000]  memory: 0f90a000 @ 006f6000 (usable)
[    0.000000] Wasting 57024 bytes for tracking 1782 unused pages
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Zone PFN ranges:
[    0.000000]   DMA      0x00000000 -> 0x00001000
[    0.000000]   Normal   0x00001000 -> 0x00010000
[    0.000000] Movable zone start PFN for each node
[    0.000000] early_node_map[1] active PFN ranges
[    0.000000]     0: 0x00000000 -> 0x00010000
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 65024
[    0.000000] Kernel command line:  console=ttyS0,38400n8r
[    0.000000] PID hash table entries: 1024 (order: 0, 4096 bytes)
[    0.000000] Dentry cache hash table entries: 32768 (order: 5, 131072 bytes)
[    0.000000] Inode-cache hash table entries: 16384 (order: 4, 65536 bytes)
[    0.000000] Primary instruction cache 2kB, VIPT, 2-way, linesize 16 bytes.
[    0.000000] Primary data cache 2kB, 2-way, VIPT, no aliases, linesize 16 bytes
[    0.000000] Writing ErrCtl register=00000000
[    0.000000] Readback ErrCtl register=00000000
[    0.000000] Memory: 252524k/255016k available (4164k kernel code, 2252k reserved, 1550k data, 220k init, 0k highmem)
[    0.000000] Hierarchical RCU implementation.
[    0.000000] NR_IRQS:256
[    0.000000] CPU frequency 199.97 MHz
[    0.000000] Console: colour dummy device 80x25
[    0.000000] Calibrating delay loop... 1241.08 BogoMIPS (lpj=2482176)
[    0.096000] Mount-cache hash table entries: 512
[    0.112000] NET: Registered protocol family 16
[    0.128000] bio: create slab <bio-0> at 0
[    0.128000] vgaarb: loaded
[    0.132000] SCSI subsystem initialized
[    0.132000] usbcore: registered new interface driver usbfs
[    0.136000] usbcore: registered new interface driver hub
[    0.136000] usbcore: registered new device driver usb
[    0.144000] pci 0000:00:0a.3: BAR 8: address space collision on of bridge [0x1100-0x110f]
[    0.148000] pci 0000:00:0a.3: quirk: region 1100-110f claimed by PIIX4 SMB
[    0.148000] vgaarb: device added: PCI:0000:00:12.0,decodes=io+mem,owns=none,locks=none
[    0.152000] pci 0000:00:0a.3: BAR 8: bogus alignment [0x1100-0x110f] flags 0x100
[    0.160000] cfg80211: Calling CRDA to update world regulatory domain
[    0.160000] Switching to clocksource MIPS
[    0.164000] NET: Registered protocol family 2
[    0.168000] Switched to NOHz mode on CPU #0
[    0.168000] IP route cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.176000] TCP established hash table entries: 8192 (order: 4, 65536 bytes)
[    0.176000] TCP bind hash table entries: 8192 (order: 3, 32768 bytes)
[    0.180000] TCP: Hash tables configured (established 8192 bind 8192)
[    0.180000] TCP reno registered
[    0.184000] NET: Registered protocol family 1
[    0.184000] PCI: Enabling device 0000:00:0a.2 (0000 -> 0001)
[    0.212000] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.216000] Registering unionfs 2.6 (for 2.6.32.63)
[    0.220000] JFFS2 version 2.2. (NAND) © 2001-2006 Red Hat, Inc.
[    0.220000] ROMFS MTD (C) 2007 Red Hat, Inc.
[    0.228000] msgmni has been set to 493
[    0.244000] alg: No test for stdrng (krng)
[    0.272000] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 253)
[    0.276000] io scheduler noop registered
[    0.276000] io scheduler cfq registered (default)
[    0.276000] firmadyne: devfs: 1, execute: 1, procfs: 1, syscall: 255
[    0.280000] firmadyne: Cannot register character device: watchdog, 0xa, 0x82!
[    0.284000] firmadyne: Cannot register character device: wdt, 0xfd, 0x0!
[    0.332000] PCI: Enabling device 0000:00:12.0 (0000 -> 0002)
[    0.336000] cirrusfb 0000:00:12.0: Cirrus Logic chipset on PCI bus, RAM (4096 kB) at 0x10000000
[    0.604000] Console: switching to colour frame buffer device 80x30
[    0.652000] Serial: 8250/16550 driver, 4 ports, IRQ sharing enabled
[    0.660000] serial8250.0: ttyS0 at I/O 0x3f8 (irq = 4) is a 16550A
[    0.668000] console [ttyS0] enabled, bootconsole disabled
[    0.668000] console [ttyS0] enabled, bootconsole disabled
[    0.672000] serial8250.0: ttyS1 at I/O 0x2f8 (irq = 3) is a 16550A
[    0.676000] serial8250.0: ttyS2 at MMIO 0x1f000900 (irq = 18) is a 16550A
[    0.688000] brd: module loaded
[    0.784000] loop: module loaded
[    0.784000] PCI: Enabling device 0000:00:0a.1 (0000 -> 0001)
[    0.828000] firmadyne: do_fork[PID: 2 (kthreadd)]: clone_flags:0x800712, stack_size:0x0
[    0.832000] firmadyne: do_fork_ret[PID: 2 (kthreadd)] = 32
[    0.832000] scsi0 : ata_piix
[    0.832000] firmadyne: do_fork[PID: 2 (kthreadd)]: clone_flags:0x800712, stack_size:0x0
[    0.940000] firmadyne: do_fork_ret[PID: 2 (kthreadd)] = 33
[    0.940000] scsi1 : ata_piix
[    0.940000] ata1: PATA max UDMA/33 cmd 0x1f0 ctl 0x3f6 bmdma 0x1040 irq 14
[    0.940000] ata2: PATA max UDMA/33 cmd 0x170 ctl 0x376 bmdma 0x1048 irq 15
[    0.940000] firmadyne: do_fork[PID: 2 (kthreadd)]: clone_flags:0x800712, stack_size:0x0
[    0.988000] firmadyne: do_fork_ret[PID: 2 (kthreadd)] = 34
[    0.988000] firmadyne: do_fork[PID: 2 (kthreadd)]: clone_flags:0x800712, stack_size:0x0
[    0.988000] firmadyne: do_fork_ret[PID: 2 (kthreadd)] = 35
[    0.988000] firmadyne: do_fork[PID: 2 (kthreadd)]: clone_flags:0x800712, stack_size:0x0
[    0.992000] firmadyne: do_fork_ret[PID: 2 (kthreadd)] = 36
[    0.992000] NAND device: Manufacturer ID: 0x98, Chip ID: 0x39 (Toshiba NAND 128MiB 1,8V 8-bit)
[    1.004000] flash size: 128 MiB
[    1.008000] page size: 512 bytes
[    1.008000] OOB area size: 16 bytes
[    1.008000] sector size: 16 KiB
[    1.008000] pages number: 262144
[    1.008000] pages per sector: 32
[    1.012000] bus width: 8
[    1.012000] bits in sector size: 14
[    1.012000] bits in page size: 9
[    1.016000] bits in OOB size: 4
[    1.016000] flash size with OOB: 135168 KiB
[    1.016000] page address bytes: 4
[    1.016000] sector address bytes: 3
[    1.020000] options: 0x62
[    1.024000] Scanning device for bad blocks
[    1.260000] Creating 1 MTD partitions on "NAND 128MiB 1,8V 8-bit":
[    1.264000] 0x000000000000-0x000008000000 : "NAND simulator partition 0"
[    1.268000] Intel(R) PRO/1000 Network Driver - version 7.3.21-k5-NAPI
[    1.316000] Copyright (c) 1999-2006 Intel Corporation.
[    1.316000] e1000e: Intel(R) PRO/1000 Network Driver - 1.0.2-k2
[    1.316000] e1000e: Copyright (c) 1999-2008 Intel Corporation.
[    1.316000] pcnet32.c:v1.35 21.Apr.2008 tsbogend@alpha.franken.de
[    1.316000] PCI: Enabling device 0000:00:0b.0 (0000 -> 0003)
[    1.316000] pcnet32: PCnet/PCI II 79C970A at 0x1020, 52:54:00:12:34:56 assigned IRQ 10.
[    1.336000] eth0: registered as PCnet/PCI II 79C970A
[    1.336000] pcnet32: 1 cards_found.
[    1.340000] PPP generic driver version 2.4.2
[    1.340000] PPP Deflate Compression module registered
[    1.356000] ata2.00: ATAPI: QEMU DVD-ROM, 2.5+, max UDMA/100
[    1.360000] ata2.00: configured for UDMA/33
[    1.380000] scsi 1:0:0:0: CD-ROM            QEMU     QEMU DVD-ROM     2.5+ PQ: 0 ANSI: 5
[    1.384000] firmadyne: do_fork[PID: 2 (kthreadd)]: clone_flags:0x800712, stack_size:0x0
[    1.392000] firmadyne: do_fork_ret[PID: 2 (kthreadd)] = 41
[    1.392000] firmadyne: do_fork[PID: 2 (kthreadd)]: clone_flags:0x800712, stack_size:0x0
[    1.396000] firmadyne: do_fork_ret[PID: 2 (kthreadd)] = 42
[    1.396000] firmadyne: do_exit[PID: 42 (cryptomgr_test)]: code:0
[    1.404000] firmadyne: do_exit[PID: 41 (cryptomgr_probe)]: code:0
[    1.408000] PPP MPPE Compression module registered
[    1.408000] NET: Registered protocol family 24
[    1.408000] PPPoL2TP kernel driver, V1.0
[    1.408000] tun: Universal TUN/TAP device driver, 1.6
[    1.412000] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[    1.412000] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    1.416000] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    1.416000] uhci_hcd: USB Universal Host Controller Interface driver
[    1.428000] uhci_hcd 0000:00:0a.2: UHCI Host Controller
[    1.428000] uhci_hcd 0000:00:0a.2: new USB bus registered, assigned bus number 1
[    1.428000] uhci_hcd 0000:00:0a.2: irq 11, io base 0x00001000
[    1.432000] usb usb1: configuration #1 chosen from 1 choice
[    1.432000] hub 1-0:1.0: USB hub found
[    1.440000] hub 1-0:1.0: 2 ports detected
[    1.440000] Initializing USB Mass Storage driver...
[    1.448000] usbcore: registered new interface driver usb-storage
[    1.448000] USB Mass Storage support registered.
[    1.452000] serio: i8042 KBD port at 0x60,0x64 irq 1
[    1.456000] serio: i8042 AUX port at 0x60,0x64 irq 12
[    1.456000] mice: PS/2 mouse device common for all mice
[    1.472000] firmadyne: do_fork[PID: 2 (kthreadd)]: clone_flags:0x800712, stack_size:0x0
[    1.472000] firmadyne: do_fork_ret[PID: 2 (kthreadd)] = 43
[    1.472000] rtc_cmos rtc_cmos: rtc core: registered rtc_cmos as rtc0
[    1.472000] rtc0: alarms up to one day, 242 bytes nvram
[    1.472000] i2c /dev entries driver
[    1.472000] piix4_smbus 0000:00:0a.3: SMBus Host Controller at 0x1100, revision 0
[    1.476000] sdhci: Secure Digital Host Controller Interface driver
[    1.476000] sdhci: Copyright(c) Pierre Ossman
[    1.476000] firmadyne: do_fork[PID: 2 (kthreadd)]: clone_flags:0x800712, stack_size:0x0
[    1.476000] firmadyne: do_fork_ret[PID: 2 (kthreadd)] = 44
[    1.476000] usbcore: registered new interface driver hiddev
[    1.476000] usbcore: registered new interface driver usbhid
[    1.480000] usbhid: v2.6:USB HID core driver
[    1.480000] Netfilter messages via NETLINK v0.30.
[    1.480000] nf_conntrack version 0.5.0 (3949 buckets, 15796 max)
[    1.484000] ctnetlink v0.93: registering with nfnetlink.
[    1.496000] IPv4 over IPv4 tunneling driver
[    1.496000] GRE over IPv4 tunneling driver
[    1.500000] ip_tables: (C) 2000-2006 Netfilter Core Team
[    1.504000] arp_tables: (C) 2002 David S. Miller
[    1.504000] TCP cubic registered
[    1.504000] Initializing XFRM netlink socket
[    1.508000] NET: Registered protocol family 10
[    1.512000] ip6_tables: (C) 2000-2006 Netfilter Core Team
[    1.520000] IPv6 over IPv4 tunneling driver
[    1.524000] NET: Registered protocol family 17
[    1.524000] Bridge firewalling registered
[    1.524000] Ebtables v2.0 registered
[    1.532000] 802.1Q VLAN Support v1.8 Ben Greear <greearb@candelatech.com>
[    1.536000] All bugs added by David S. Miller <davem@redhat.com>
[    1.536000] lib80211: common routines for IEEE802.11 drivers
[    1.540000] rtc_cmos rtc_cmos: setting system clock to 2019-04-17 07:48:20 UTC (1555487300)
[    1.576000] input: AT Raw Set 2 keyboard as /devices/platform/i8042/serio0/input/input0
[    1.820000] input: ImExPS/2 Generic Explorer Mouse as /devices/platform/i8042/serio1/input/input1
[    1.820000] firmadyne: vfs_unlink[PID: 1 (swapper)]: file:ram
[    1.820000] firmadyne: vfs_mknod[PID: 1 (swapper)]: file:ram major:1 minor:0
[    1.820000] firmadyne: open[PID: 1 (swapper)]: file:/dev/ram
[    1.832000] firmadyne: open[PID: 1 (swapper)]: file:/initrd.image
[    1.840000] firmadyne: close[PID: 1 (swapper)]: fd:0
[    1.848000] firmadyne: vfs_unlink[PID: 1 (swapper)]: file:ram
[    1.848000] firmadyne: vfs_unlink[PID: 1 (swapper)]: file:initrd.image
[    1.848000] firmadyne: vfs_unlink[PID: 1 (swapper)]: file:root
[    1.848000] firmadyne: vfs_mknod[PID: 1 (swapper)]: file:root major:0 minor:0
[    1.848000] firmadyne: do_mount[PID: 1 (swapper)]: mountpoint:/root, device:/dev/root, type:ext3
[    1.852000] VFS: Cannot open root device "<NULL>" or unknown-block(0,0)
[    1.852000] Please append a correct "root=" boot option; here are the available partitions:
[    1.852000] 1f00          131072 mtdblock0 (driver?)
[    1.852000] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)

**Comment by ddcc** [comment]
Yes, it seems there are some issues with firmadyne's kernel for arm.

**Comment by canance** [comment]
Try using an older version of qemu.  I've had good luck getting output with the arm kernel on qemu 2.5.0 and 2.6.0.  I've also noticed on newer versions of qemu, such as 2.12.0, that I don't get any output.

**Comment by MatthewShao** [comment]
To whom get into this problem:
You could specify an older machine type with option `-M virt-2.10` to boot it up with newer versions of qemu.

**Comment by ddcc** [comment]
After some testing, I've verified that 2.6.2 is the latest version that works for the ARM kernel. Unfortunately, even specifying virt-2.6 with newer versions of QEMU doesn't work.

**Comment by 31ackhawk** [comment]
Same problem with QEMU emulator version 4.2.1 (Debian 1:4.2-3ubuntu6.14), but use the -M virt-2.6 parameter helped.
It causes the ./scripts/inferNetwork.sh  script give empty network parameters like this:
 processing 1
Candidate ifaces: <filter object at 0xffff9c361ca0>
Mac Changes <filter object at 0xffff9c361ca0>
Interfaces: []

After i changed the parameter mentioned above in the  /scripts/run.armel.sh script:
processing 1
Candidate ifaces: <filter object at 0xffff85671d60>
Mac Changes <filter object at 0xffff857a3820>
Interfaces: [('eth0', '192.168.100.1')]
brifs for eth0 []
Done!

**Comment by AndrewFasano** [comment]
I tracked down the root cause of this issue to the `COFNIG_DEBUG_LL` flag being set in the provided `config.armel` file for the firmadyne kernel. If the kernel is built with that option disabled, I'm able to get guest output as expected by running
```
$ qemu-system-arm -M virt -kernel ./build/armel/arch/arm/boot/zImage -nographic
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.1.17+ (fasano@host) (gcc version 5.3.0 (GCC) ) #1 Thu Apr 8 14:33:23 EDT 2021
[    0.000000] CPU: ARMv7 Processor [412fc0f1] revision 1 (ARMv7), cr=10c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, PIPT instruction cache
...
```

Tested under qemu-system-arm version `2.11.1(Debian 1:2.11+dfsg-1ubuntu7.36)`.

I opened a PR with the fix: https://github.com/firmadyne/kernel-v4.1/pull/1

**Comment by AndrewFasano** [comment]
That kernel works for me. Thanks for the quick merge and release!
