### ISSUE TITLE
'mips64eb' makeImages.sh error!

### ISSUE THREAD

**Issue by Vxer-Lee** [firmadyne/firmadyne#108]
**H3C Router**
Download ER5200-MNW100-R1116.zip
[ER5200-MNW100-R1116.zip](http://download.h3c.com.cn/download.do?id=3214179)

`> ./scripts/getArch.sh ./images/10.tar.gz `
`./bin/busybox: mips64eb`

---------------------------------------------------------------------------------------------------

`> sudo ./scripts/makeImage.sh 10`
`Querying database for architecture... Password for user firmadyne: `
`mips64eb`
`----Running----`

-----------------------------------------------------------------------------------------------------

`> ./scripts/inferNetwork.sh 10`
`Querying database for architecture... Password for user firmadyne: `
`mips64eb`
`Running firmware 10: terminating after 60 secs...`
`timeout: failed to run command ‘/home/oit/tools/firmadyne//scripts//run.mips64eb.sh’: No such file or directory`

**Comment by ddcc** [comment]
Unfortunately, 64-bit MIPS targets are not supported

**Comment by Vxer-Lee** [comment]
Thank you!
