### ISSUE TITLE
Incorrect use of .iteritems() in scripts/tar2db.py

### ISSUE THREAD

**Issue by gal0is** [firmadyne/firmadyne#109]
I encountered the following error. I think the code in scripts/tar2db.py should be update since iteritems() was removed in python3.7

```
Traceback (most recent call last):
  File "./scripts/tar2db.py", line 100, in <module>
    main()
  File "./scripts/tar2db.py", line 97, in main
    process(iid, infile)
  File "./scripts/tar2db.py", line 75, in process
    file2oid = [(fdict[h], oid) for (h, oid) in oids.iteritems()]
AttributeError: 'dict' object has no attribute 'iteritems'
```

The code in line75 should be modified to

`file2oid = [(fdict[h], oid) for (h, oid) in oids.items()]`

**Comment by ddcc** [comment]
Thanks, I don't think we've tested much with python3. Please submit a pull request, I'd just suggest using `six.iteritems()` to maintain compatibility with both python2 and python3.

**Comment by ddcc** [comment]
Thanks!
