### ISSUE TITLE
Please update syntax for network setup

### ISSUE THREAD

**Issue by CJHackerz** [firmadyne/firmadyne#119]
https://github.com/firmadyne/firmadyne/blob/5bd542f1bb435d432159138d65bdd54f7a818ff8/scripts/makeNetwork.py#L136-L150

According to [this](https://www.qemu.org/2018/05/31/nic-parameter/) post from QEMU, it's clear that vlan option is not supported any more in the latest version of qemu software. Whenever new folks in IoT security discovers firmadyne all people are struggling to run it in since many are not aware that firmadyne will only work with before QEMU v3.0 and current latest stable is [v4.1.0](https://github.com/qemu/qemu/tree/v4.1.0) currently as a time of writing this issue. You have two options, update code of makeNetwork.py file or mention in README.md that firmadyne will only work with older versions of QEMU before V3.0

**Comment by ddcc** [comment]
Unfortunately, I haven't had the time to develop firmadyne since the original release, so I have added a note about the version. If you (or anyone interested) is interested in contributing patches, I'm happy to merge them.
