### ISSUE TITLE
bind: Address already in use

### ISSUE THREAD

**Issue by smhome** [firmadyne/firmadyne#13]
Hi,

when I run
`./scripts/inferNetwork.sh 1`
I get the following response:

> Querying database for architecture... armel
Running firmware 1: terminating after 60 secs...
bind: Address already in use
qemu-system-arm: -netdev socket,listen=:2001,id=net2: Device 'socket' could not be initialized

What could be the reason? 
Thanks a lot.

**Comment by ddcc** [comment]
It sounds like something else is already listening on localhost:2001. Do you have another instance of QEMU running? Alternatively, you can modify the script to listen on a different port.

**Comment by smhome** [comment]
You were right. 
Thanks a lot!
