### ISSUE TITLE
Request the firmwares (bin) which can be emulated

### ISSUE THREAD

**Issue by gunheenoh** [firmadyne/firmadyne#132]
Hello, we appreciate that you made the firmadyne.
We are trying to emulate several firmwares, but most of firmwares are failed to load.

So, we like to compare between loadable firmwares and unloadable firmwares.
However, it is hard to get the firmwares which are listed in Readme of analysis folder.

Sharing the firmware binary you have will be very helpful to us.
Thank you all.

**Comment by ddcc** [comment]
There have been some recent bugs that may have impacted emulation.

We don't have our original dataset anymore, and even if we did, we can't redistribute them for copyright reasons.
