### ISSUE TITLE
Accessing the dataset of firmware

### ISSUE THREAD

**Issue by heshananupama** [firmadyne/firmadyne#144]
Hi,
I am masters student, working in a research related to embedded firmware reverse engineering. For our work, we are in need of a dataset and after going through your papers I realized that it would be great if we could access the set of firmware that you already crawled and downloaded. Is there a way to access these? I tried going to the github repo but could not find the set of firmware that you had been used. Thank you.

**Comment by ddcc** [comment]
Sorry, I don't have the dataset, and we can't redistribute it due to copyright. You can look at the provided database dump to see which firmware were tested, and run the scraper to crawl and download firmware.

**Comment by heshananupama** [comment]
Thanks Dominic. Is this the schema under the database folder? I could not locate a dump other than the schema

**Comment by ddcc** [comment]
No, it is this link in the README: https://github.com/firmadyne/firmadyne#data

**Comment by heshananupama** [comment]
Thank you Dominic!
