### ISSUE TITLE
Unable to login to netgear123456

### ISSUE THREAD

**Issue by lasur2** [firmadyne/firmadyne#146]
Hi there,

I am a newbie  and trying to setup and practice on tis tool.

I have followed the usage instructions on the github

I did unmount the file system but can't find /etc/securetty from the filesystem to delete. 

login as root with password password fails!

Any pointers to solve this appreciated.

**Comment by ddcc** [comment]
Did you mount (not unmount) the filesystem?

**Comment by lasur2** [comment]
I rebuilt the image sudo ./scripts/makeImage.sh 1  and  followed the instructions. It worked this time !
Thanks for the respone.
