### ISSUE TITLE
No network interface

### ISSUE THREAD

**Issue by anesic-c4** [firmadyne/firmadyne#196]
All commands works fine, I even start firmware, but I never get Interface and IP address for emulated firmware. 
I used example_analysis.sh also, but no interface is running neither.
There is no any particular error. 
This is when command is ran. 

sudo ./scripts/inferNetwork.sh 2 mipsel
Running firmware 2: terminating after 60 secs...
qemu-system-mipsel: terminating on signal 2 from pid 32122 (timeout)
Inferring network...
Interfaces: []
Done!

Thanks in advance.

**Comment by HAHALOSAH** [comment]
I'm also having this problem, how do I fix it?

**Comment by ThomEsgate** [comment]
I'm also having this problem

**Comment by yejuns** [comment]
I'm also having this problem, i have tried to config network, but it didn't work
