### ISSUE TITLE
Error in makeImage.sh

### ISSUE THREAD

**Issue by h4sv0c** [firmadyne/firmadyne#201]
An error occurred when the command was executed as shown in the following figure.
I ran this command on ubutnu21.

![image](https://user-images.githubusercontent.com/80557170/197321901-4c12125b-e467-4780-8e5d-cd90d05596c1.png)

This is thought to be caused by the command at line 63 of makeImage.sh.
When I executed the command on line 63, I got the following result.

![image](https://user-images.githubusercontent.com/80557170/197322446-1bf95a33-344c-497a-959e-f33e74039963.png)

However, this resulted in an error at line 64, so the error did not occur when the command was changed as shown below.

![image](https://user-images.githubusercontent.com/80557170/197322501-fa67857c-d650-47e5-b48b-96d718d7921c.png)

So I propose to change line 63 as follows

`TARBALL_SIZE=$(tar ztvf "${TARBALL_DIR}/${IID}.tar.gz" --totals 2>&1 |tail -1|cut -f4 -d' ')`
↓
`TARBALL_SIZE=$(tar ztvf "${TARBALL_DIR}/${IID}.tar.gz" --totals 2>&1 |tail -1|cut -f4 -d' '| sed -e 's/MiB\/s)//g')`

**Comment by ddcc** [comment]
I don't think that's right, it should be grabbing the raw size and not the decompression rate. e.g. in the following:
```
Total bytes read: 1187840 (1.2MiB, 147MiB/s)
```

The goal of `tar ztvf {file} --totals 2>&1 | tail -1 | cut -f4 -d ' '` is to fetch the 1187840 field.

**Comment by h4sv0c** [comment]
It seems to be due to the fact that the execution result contained Japanese characters.
![image](https://user-images.githubusercontent.com/80557170/197323714-40442de2-957e-4220-8ca8-9b17754fc50c.png)

Now that we know how to fix it, please CLOSE it.

Thank you for your quick response!

**Comment by h4sv0c** [comment]
I'm going to CLOSE this as it has been resolved.
