### ISSUE TITLE
inferNetwork.sh UnicodeDecodeError

### ISSUE THREAD

**Issue by iAmG-r00t** [firmadyne/firmadyne#207]
I am trying to emulate this router [image](http://www.netis-systems.com/Suppory/downloads/dd/1/img/75) but I am getting this error while trying to run the ***inferNetwork.sh*** script. Tried to fix it but I can't see the `codecs.decode(var, 'utf-8')` line so am really confused now.

![image](https://user-images.githubusercontent.com/29776892/213797522-addeb862-9c36-4eb1-9201-d0b17e44b911.png)

**Comment by iAmG-r00t** [comment]
So I can see you can get this error while also trying to open a file [source](https://stackoverflow.com/questions/16528468/while-reading-file-on-python-i-got-a-unicodedecodeerror-what-can-i-do-to-resol)

**Comment by iAmG-r00t** [comment]
Okay this `data = open(infile, encoding='iso-8859-15').read()` fixes it. I think we should place a try ... except using various types of encoding types

**Comment by iAmG-r00t** [comment]
But still unable to emulate the image because it does not have an `/etc/init.d/rcS` or `/etc/rcS.sh` file

**Comment by hackinaggie** [comment]
Changing the encoding worked for me as well. Easy little workaround for when the firmware's init scripts give bad output.
