### ISSUE TITLE
makeNetwork.sh line 182 dev error

### ISSUE THREAD

**Issue by icepng** [firmadyne/firmadyne#27]
some firewares return dev is not eth0 or eth1 but ethlan, how can i modify it in line 193.

**Comment by ddcc** [comment]
Which file are you referring to? I don't believe it matters which network device the firmware itself refers to; on the host system, it will accessible through `tap*`.

**Comment by icepng** [comment]
netgear/R7800/R7800-V1.0.2.04.img

**Comment by ddcc** [comment]
The crash should be fixed now.
