### ISSUE TITLE
Generated run.sh does not exit properly

### ISSUE THREAD

**Issue by dfbravo** [firmadyne/firmadyne#35]
The run.sh generated by inferNetwork.sh does not exist properly. When you use ctrl-a + x to exit QEMU, the cleanup function is not called. I suspected it is due to qemu command exiting with a non-zero status causing the run.sh to exit prematurely. 

I added `set +e` before the following line in run.sh and the cleanup function was actually called. Now the issue I saw is that it seems to be called twice. 

```
 ${QEMU} -m 256 -M ${QEMU_MACHINE} -kernel ${KERNEL} \
    -drive if=ide,format=raw,file=${IMAGE} -append "root=${QEMU_ROOTFS} console=ttyS0 nandsim.parts=64,64,64,64,64,64,64,64,64,64 rdinit=/preInit.sh rw debug ignore_loglevel print-fatal-signals=1 user_debug=31 firmadyne.syscall=8" \
    -nographic \
    -net nic,vlan=0 -net socket,vlan=0,listen=:2000 -net nic,vlan=1 -net tap,vlan=1,id=net0,ifname=${TAPDEV_0},script=no -net nic,vlan=2 -net socket,vlan=2,listen=:2002 -net nic,vlan=3 -net socket,vlan=3,listen=:2003 | tee ${WORK_DIR}/qemu.final.serial.log
```

**Comment by ddcc** [comment]
Thanks for catching that!
