### ISSUE TITLE
run.sh generate by makeNetwork.py uses wrong path for preInit.sh

### ISSUE THREAD

**Issue by dfbravo** [firmadyne/firmadyne#39]
The run.sh generated by makeNetwork.py uses the wrong path for preInit.sh in the rdinit kernel argument:

```
rdinit=/preInit.sh
```
The correct path should be:
```
rdinit=/firmadyne/preInit.sh
```
Which is the same path used by the run scripts in `firmadyne/scripts/`

**Comment by ddcc** [comment]
Thanks, fixed.
