### ISSUE TITLE
MIPS From Source

### ISSUE THREAD

**Issue by ksbickmore** [firmadyne/firmadyne#45]
Working on Ubuntu 16.04.2 Xenial.
I've built the ARM kernel from source without any problems.  I'm currently trying to build the big-endian MIPS kernel and I'm getting the following error.

Can't use 'defined(@array)' (Maybe you should just omit the defined()?) at /home/user/firmadyne/kernel-v2.6.32/kernel/timeconst.pl line 373.
  CC      arch/mips/math-emu/dp_tlong.o
/home/user/firmadyne/kernel-v2.6.32/kernel/Makefile:129: recipe for target 'kernel/timeconst.h' failed
make[2]: *** [kernel/timeconst.h] Error 255
/home/user/firmadyne/kernel-v2.6.32/Makefile:883: recipe for target 'kernel' failed
make[1]: *** [kernel] Error 2
make[1]: *** Waiting for unfinished jobs....

I've searched around for similar problems and most of them say I need to install BC; however, that has already been installed.  Any help would be appreciated.

**Comment by ddcc** [comment]
Not really a firmadyne bug, but from the upstream kernel and apparently has to do with a perl language feature being deprecated. Either use a version of perl < 5.22, or apply the upstream patch: https://lkml.org/lkml/2012/11/18/159
