### ISSUE TITLE
netgear123456 login failure

### ISSUE THREAD

**Issue by ykddd** [firmadyne/firmadyne#48]
After deleting the the file /etc/securetty,I still can't log in with root ang password.

Welcome to SDK.

Have a lot of fun...

netgear123456 login: root
Login incorrect

why?

**Comment by ddcc** [comment]
Did you unmount the filesystem after mounting it? If you remount the filesystem, is the file `/etc/securetty` gone? Can you try deleting the QEMU disk and restarting from make image?

**Comment by ykddd** [comment]
I make a mistake that forgeting to mount the filesystem ,I directly delete the /etc/securetty in my computer not the /etc/securetty in the filesystem.......I am so stupid....

**Comment by richprice36** [comment]
So I have tryed everyting I can find to figure out how to login as root to the demo WNAP320.  I have it running and can login to the AP website etc..  When as for user I type root but the prompt never asks for a password.  Not sure what to do here..
