### ISSUE TITLE
Firmware "WNAP320_V3.7.9.0_firmware",infernetwork error.

### ISSUE THREAD

**Issue by ftk-sostupid** [firmadyne/firmadyne#76]
When I emulate the "WNAP320_V3.7.9.0_firmware"(Download link http://support.netgear.cn/Upfilepath/WNAP320_V3.7.9.0_firmware.tar), I got this error:
![default](https://user-images.githubusercontent.com/30171892/38801675-13b0963c-419d-11e8-9dbb-855545bf117f.png)
If I ignored this and run the ./scratch/2/run.sh, it shows like:
![default](https://user-images.githubusercontent.com/30171892/38801739-423f6460-419d-11e8-9f17-eb777277df6b.png)
And then it just stopped, the emulation failed either.
Before this I emulated the example(WNAP320 Firmware Version 2.0.3.zip) soon after.
This caused by the firmware's file format or some other errors? How can I resolve this?
Sorry for my bad English.

**Comment by ftk-sostupid** [comment]
I've resolved this problem. The firmware format should be tar or zip, and inside should be like:
![default](https://user-images.githubusercontent.com/30171892/38846010-bbddef6e-422c-11e8-9d1a-bc300aaf5fc2.png)
I unziped the former firmware, then the right firmware file comes to me.

**Comment by ddcc** [comment]
Glad you figured it out. The extractor script should take care of storing the firmware in the correct format.
