### ISSUE TITLE
makeNetwork.py Error

### ISSUE THREAD

**Issue by fengmubai** [firmadyne/firmadyne#96]
The "vlan" parameter to -net was deprecated in QEMU 2.9.0 and removed in a subsequent release. 

The obsolete -net syntax automatically created an emulated hub with ID 0 (used to be called a "VLAN" in older versions of QEMU, for virtual LAN) that forwards traffic from any device connected to it to every other device on the "VLAN". If you need more than one hub in recent versions of QEMU, you can do this with the "hubport" backend, e.g. by using -nic hubport,hubid=1.

from https://wiki.qemu.org/Documentation/Networking

**Comment by ddcc** [comment]
Thanks for the report; I haven't had the time to change it around and test it. Someone else reported the same issue in #88, it sounded like 2.12.1 still worked.
