### ISSUE TITLE
Most firmwares are able to be extracted?

### ISSUE THREAD

**Issue by hehe1397** [firmadyne/firmadyne#99]

**Comment by hehe1397** [comment]
I used the spiders to crawl a lot of firmware, but just a few firmware can be extracted. And fewer can be found the vulnerabilities. Is it normal?

**Comment by cq674350529** [comment]
`binwalk` is great. But in general, there are many firmwares which `binwalk` can't handle. The most common situation is that when firmware is encrypted. In that situation, you have to decrypt the firmware first before analyzing it.

**Comment by ddcc** [comment]
Yes, we had a fairly low success rate as well. I forget the exact numbers, but they are in the paper. Due to the diversity of devices, it's difficult to fully automate the entire process without more development work.

**Comment by hehe1397** [comment]
> `binwalk` is great. But in general, there are many firmwares which `binwalk` can't handle. The most common situation is that when firmware is encrypted. In that situation, you have to decrypt the firmware first before analyzing it.

Thanks for your help, I'll try it

**Comment by hehe1397** [comment]
> Yes, we had a fairly low success rate as well. I forget the exact numbers, but they are in the paper. Due to the diversity of devices, it's difficult to fully automate the entire process without more development work.

**Comment by hehe1397** [comment]
> Yes, we had a fairly low success rate as well. I forget the exact numbers, but they are in the paper. Due to the diversity of devices, it's difficult to fully automate the entire process without more development work.

OK, I understand it. Thank you
